variables:
  AWS_REGION: "us-east-1"
  AWS_CLOUD_CI_ROLE_ARN: "arn:aws:iam::211125629230:role/TiledbCloudPyCIRole"
  AWS_CLOUD_CI_S3_BUCKET: "tiledb-cloud-py-ci"

stages:
  - aws-assume-role
  - run-tests

aws-assume-role:
  # Assume role and override AWS env variables
  stage: aws-assume-role
  image:
    name: "amazon/aws-cli:latest"
    entrypoint: [""]
  before_script:
    - >
      export $(printf "AWS_ACCESS_KEY_ID=%s AWS_SECRET_ACCESS_KEY=%s AWS_SESSION_TOKEN=%s"
      $(aws sts assume-role
      --role-arn ${AWS_CLOUD_CI_ROLE_ARN}
      --role-session-name "GitLabRunner-${CI_PROJECT_ID}-${CI_PIPELINE_ID}"
      --duration-seconds 3600
      --query 'Credentials.[AccessKeyId,SecretAccessKey,SessionToken]'
      --output text))
  script:
    - aws s3 ls s3://${AWS_CLOUD_CI_S3_BUCKET}
    # Write AWS ENV Variables to run-tests.env for use in the next stages
    - echo "AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID" >> run-tests.env
    - echo "AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY" >> run-tests.env
    - echo "AWS_SESSION_TOKEN=$AWS_SESSION_TOKEN" >> run-tests.env
  artifacts:
    expire_in: "30 min"
    reports:
      dotenv: run-tests.env

run-tests:
  stage: run-tests
  image: python:3.9-slim
  needs:
    - aws-assume-role
  before_script:
    - apt-get update && apt-get install -y git
    - pip install --upgrade pip wheel setuptools setuptools-scm
    - pip install .[tests]
    - pip install tiledb-vector-search --no-deps
    # Export ENV Variables from aws-assume-role stage
    - export "AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID"
    - export "AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY"
    - export "AWS_SESSION_TOKEN=$AWS_SESSION_TOKEN"
  script:
    - >
      pytest -sv tests/gitlab_tests
      --tb short
      --color yes
