image: ubuntu:latest

variables:
  AWS_REGION: "us-east-1"
  AWS_CLOUD_CI_ROLE_ARN: "arn:aws:iam::211125629230:role/TiledbCloudPyCIRole"
  AWS_CLOUD_CI_S3_BUCKET: "tiledb-cloud-py-ci"

stages:
  - aws-credentials
  - check-aws-credentials

.aws-cli:
  image:
    name: "amazon/aws-cli:latest"
    entrypoint: [""]

aws-credentials:
  stage: aws-credentials
  extends: .aws-cli
  script:
    - >
      export $(printf "AWS_ACCESS_KEY_ID=%s AWS_SECRET_ACCESS_KEY=%s AWS_SESSION_TOKEN=%s"
      $(aws sts assume-role
      --role-arn ${AWS_CLOUD_CI_ROLE_ARN}
      --role-session-name "GitLabRunner-${CI_PROJECT_ID}-${CI_PIPELINE_ID}"
      --duration-seconds 3600
      --query 'Credentials.[AccessKeyId,SecretAccessKey,SessionToken]'
      --output text))
    # - aws sts get-caller-identity
    - aws s3 ls s3://${AWS_CLOUD_CI_S3_BUCKET}
  # artifacts:
  #   reports:
  #     dotenv: aws.env
  #   expire_in: 30min
# check-aws-credentials:
#   stage: check-aws-credentials
#   extends: .aws-cli
#   dependencies:
#     - aws-credentials
#   script:
