image: ubuntu:latest

variables:
  AWS_REGION: "us-east-1"
  AWS_ROLE_ARN: "arn:aws:iam::211125629230:role/TiledbCloudPyCIRole"
  AWS_S3_BUCKET: "tiledb-cloud-py-ci"

stages:
  - aws-credentials
  - check-aws-credentials

.aws-cli:
  image:
    name: "amazon/aws-cli:latest"
    entrypoint: [""]

aws-credentials:
  stage: aws-credentials
  extends: .aws-cli
  script:
    - >
      export $(printf "AWS_ACCESS_KEY_ID=%s AWS_SECRET_ACCESS_KEY=%s AWS_SESSION_TOKEN=%s"
      $(aws sts assume-role
      --role-arn gitlab-runners-role
      --role-session-name "GitLabRunner-${CI_PROJECT_ID}-${CI_PIPELINE_ID}"
      --duration-seconds 3600
      --query 'Credentials.[AccessKeyId,SecretAccessKey,SessionToken]'
      --output text))
    - aws sts get-caller-identity
    - echo $AWS_ACCESS_KEY
    - echo $AWS_SECRET_ACCESS_KEY
    - echo $AWS_SESSION_TOKEN
  # artifacts:
  #   reports:
  #     dotenv: aws.env
  #   expire_in: 30min

check-aws-credentials:
  stage: check-aws-credentials
  # needs: [aws-oidc-credentials]
  extends: .aws-cli
  dependencies:
    - aws-credentials
  script:
    - aws s3 ls s3://${AWS_S3_BUCKET}
