# Don't build any extra formats
formats: []

# Use RTD config version 2
# https://docs.readthedocs.io/en/stable/config-file/v2.html
version: 2

sphinx:
  configuration: docs/source/conf.py

python:
  version: 3.9
  install:
    - requirements: docs/requirements.txt
    - method: setuptools
      path: .
