# coding: utf-8

"""
    Tiledb Storage Platform API

    TileDB Storage Platform REST API  # noqa: E501

    The version of the OpenAPI document: 1.4.0
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import tiledb.cloud.rest_api
from tiledb.cloud.rest_api.models.group_metadata_update_request import GroupMetadataUpdateRequest  # noqa: E501
from tiledb.cloud.rest_api.rest import ApiException

class TestGroupMetadataUpdateRequest(unittest.TestCase):
    """GroupMetadataUpdateRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test GroupMetadataUpdateRequest
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # model = tiledb.cloud.rest_api.models.group_metadata_update_request.GroupMetadataUpdateRequest()  # noqa: E501
        if include_optional :
            return GroupMetadataUpdateRequest(
                config = tiledb.cloud.rest_api.models.tile_db_config.TileDBConfig(
                    entries = [
                        tiledb.cloud.rest_api.models.tile_db_config_entries.TileDBConfig_entries(
                            key = '0', 
                            value = '0', )
                        ], ), 
                metadata = tiledb.cloud.rest_api.models.metadata.Metadata(
                    entries = [
                        tiledb.cloud.rest_api.models.metadata_entry.MetadataEntry(
                            key = '0', 
                            type = '0', 
                            value_num = 56, 
                            value = tiledb.cloud.rest_api.models.value.value(), 
                            del = True, )
                        ], )
            )
        else :
            return GroupMetadataUpdateRequest(
                metadata = tiledb.cloud.rest_api.models.metadata.Metadata(
                    entries = [
                        tiledb.cloud.rest_api.models.metadata_entry.MetadataEntry(
                            key = '0', 
                            type = '0', 
                            value_num = 56, 
                            value = tiledb.cloud.rest_api.models.value.value(), 
                            del = True, )
                        ], ),
        )

    def testGroupMetadataUpdateRequest(self):
        """Test GroupMetadataUpdateRequest"""
        inst_req_only = self.make_instance(include_optional=False)
        inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == '__main__':
    unittest.main()
