# coding: utf-8

"""
    Specification file for tiledb-server v4 API

    This spec is exposed to the public under /v4 route group  # noqa: E501

    The version of the OpenAPI document: 0.0.1
    Contact: info@tiledb.com
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six

from tiledb.cloud._common.api_v4.configuration import Configuration


class TeamspaceUpdateRequest(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        "name": "str",
        "description": "str",
        "icon": "str",
        "visibility_level": "TeamspaceVisibility",
    }

    attribute_map = {
        "name": "name",
        "description": "description",
        "icon": "icon",
        "visibility_level": "visibility_level",
    }

    def __init__(
        self,
        name=None,
        description=None,
        icon=None,
        visibility_level=None,
        local_vars_configuration=None,
    ):  # noqa: E501
        """TeamspaceUpdateRequest - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration()
        self.local_vars_configuration = local_vars_configuration

        self._name = None
        self._description = None
        self._icon = None
        self._visibility_level = None
        self.discriminator = None

        if name is not None:
            self.name = name
        if description is not None:
            self.description = description
        if icon is not None:
            self.icon = icon
        if visibility_level is not None:
            self.visibility_level = visibility_level

    @property
    def name(self):
        """Gets the name of this TeamspaceUpdateRequest.  # noqa: E501

        The teamspace name  # noqa: E501

        :return: The name of this TeamspaceUpdateRequest.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this TeamspaceUpdateRequest.

        The teamspace name  # noqa: E501

        :param name: The name of this TeamspaceUpdateRequest.  # noqa: E501
        :type: str
        """

        self._name = name

    @property
    def description(self):
        """Gets the description of this TeamspaceUpdateRequest.  # noqa: E501

        The teamspace description  # noqa: E501

        :return: The description of this TeamspaceUpdateRequest.  # noqa: E501
        :rtype: str
        """
        return self._description

    @description.setter
    def description(self, description):
        """Sets the description of this TeamspaceUpdateRequest.

        The teamspace description  # noqa: E501

        :param description: The description of this TeamspaceUpdateRequest.  # noqa: E501
        :type: str
        """

        self._description = description

    @property
    def icon(self):
        """Gets the icon of this TeamspaceUpdateRequest.  # noqa: E501

        The teamspace icon as a UTF8-encoded Unicode symbol, e.g. 🚀  # noqa: E501

        :return: The icon of this TeamspaceUpdateRequest.  # noqa: E501
        :rtype: str
        """
        return self._icon

    @icon.setter
    def icon(self, icon):
        """Sets the icon of this TeamspaceUpdateRequest.

        The teamspace icon as a UTF8-encoded Unicode symbol, e.g. 🚀  # noqa: E501

        :param icon: The icon of this TeamspaceUpdateRequest.  # noqa: E501
        :type: str
        """

        self._icon = icon

    @property
    def visibility_level(self):
        """Gets the visibility_level of this TeamspaceUpdateRequest.  # noqa: E501


        :return: The visibility_level of this TeamspaceUpdateRequest.  # noqa: E501
        :rtype: TeamspaceVisibility
        """
        return self._visibility_level

    @visibility_level.setter
    def visibility_level(self, visibility_level):
        """Sets the visibility_level of this TeamspaceUpdateRequest.


        :param visibility_level: The visibility_level of this TeamspaceUpdateRequest.  # noqa: E501
        :type: TeamspaceVisibility
        """

        self._visibility_level = visibility_level

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(
                    map(lambda x: x.to_dict() if hasattr(x, "to_dict") else x, value)
                )
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(
                    map(
                        lambda item: (item[0], item[1].to_dict())
                        if hasattr(item[1], "to_dict")
                        else item,
                        value.items(),
                    )
                )
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, TeamspaceUpdateRequest):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, TeamspaceUpdateRequest):
            return True

        return self.to_dict() != other.to_dict()
