# coding: utf-8

"""
    TileDB Storage Platform API

    TileDB Storage Platform REST API  # noqa: E501

    The version of the OpenAPI document: 2.0.12
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import rest_api
from tiledb.cloud.rest_api.models.udf_info_update import UDFInfoUpdate  # noqa: E501
from tiledb.cloud.rest_api.rest import ApiException


class TestUDFInfoUpdate(unittest.TestCase):
    """UDFInfoUpdate unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testUDFInfoUpdate(self):
        """Test UDFInfoUpdate"""
        # FIXME: construct object with mandatory attributes with example values
        # model = tiledb.cloud.rest_api.models.udf_info_update.UDFInfoUpdate()  # noqa: E501
        pass


if __name__ == "__main__":
    unittest.main()
