"""
    TileDB Storage Platform API

    TileDB Storage Platform REST API  # noqa: E501

    The version of the OpenAPI document: 2.2.19
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import tiledb.cloud.rest_api
from tiledb.cloud.rest_api.model.filter_type import FilterType


class TestFilterType(unittest.TestCase):
    """FilterType unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testFilterType(self):
        """Test FilterType"""
        # FIXME: construct object with mandatory attributes with example values
        # model = FilterType()  # noqa: E501
        pass


if __name__ == "__main__":
    unittest.main()
