# coding: utf-8

"""
    TileDB Storage Platform API

    TileDB Storage Platform REST API  # noqa: E501

    The version of the OpenAPI document: 0.6.3
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import rest_api
from tiledb.cloud.rest_api.models.array import Array  # noqa: E501
from tiledb.cloud.rest_api.rest import ApiException


class TestArray(unittest.TestCase):
    """Array unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testArray(self):
        """Test Array"""
        # FIXME: construct object with mandatory attributes with example values
        # model = tiledb.cloud.rest_api.models.array.Array()  # noqa: E501
        pass


if __name__ == "__main__":
    unittest.main()
