"""
    TileDB Storage Platform API

    TileDB Storage Platform REST API  # noqa: E501

    The version of the OpenAPI document: 2.2.19
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import tiledb.cloud.rest_api
from tiledb.cloud.rest_api.model.group_member_type import GroupMemberType

globals()["GroupMemberType"] = GroupMemberType
from tiledb.cloud.rest_api.model.group_member import GroupMember


class TestGroupMember(unittest.TestCase):
    """GroupMember unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testGroupMember(self):
        """Test GroupMember"""
        # FIXME: construct object with mandatory attributes with example values
        # model = GroupMember()  # noqa: E501
        pass


if __name__ == "__main__":
    unittest.main()
