"""
    TileDB Storage Platform API

    TileDB Storage Platform REST API  # noqa: E501

    The version of the OpenAPI document: 2.2.19
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import tiledb.cloud.rest_api
from tiledb.cloud.rest_api.model.subarray import Subarray

globals()["Subarray"] = Subarray
from tiledb.cloud.rest_api.model.subarray_partitioner_current import (
    SubarrayPartitionerCurrent,
)


class TestSubarrayPartitionerCurrent(unittest.TestCase):
    """SubarrayPartitionerCurrent unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testSubarrayPartitionerCurrent(self):
        """Test SubarrayPartitionerCurrent"""
        # FIXME: construct object with mandatory attributes with example values
        # model = SubarrayPartitionerCurrent()  # noqa: E501
        pass


if __name__ == "__main__":
    unittest.main()
