"""
    TileDB Storage Platform API

    TileDB Storage Platform REST API  # noqa: E501

    The version of the OpenAPI document: 2.2.19
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import tiledb.cloud.rest_api
from tiledb.cloud.rest_api.model.array_actions import ArrayActions
from tiledb.cloud.rest_api.model.file_type import FileType
from tiledb.cloud.rest_api.model.pricing import Pricing
from tiledb.cloud.rest_api.model.subscription import Subscription

globals()["ArrayActions"] = ArrayActions
globals()["FileType"] = FileType
globals()["Pricing"] = Pricing
globals()["Subscription"] = Subscription
from tiledb.cloud.rest_api.model.array_info import ArrayInfo


class TestArrayInfo(unittest.TestCase):
    """ArrayInfo unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testArrayInfo(self):
        """Test ArrayInfo"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ArrayInfo()  # noqa: E501
        pass


if __name__ == "__main__":
    unittest.main()
