"""
    TileDB Storage Platform API

    TileDB Storage Platform REST API  # noqa: E501

    The version of the OpenAPI document: 2.2.19
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import tiledb.cloud.rest_api
from tiledb.cloud.rest_api.model.namespace_actions import NamespaceActions


class TestNamespaceActions(unittest.TestCase):
    """NamespaceActions unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testNamespaceActions(self):
        """Test NamespaceActions"""
        # FIXME: construct object with mandatory attributes with example values
        # model = NamespaceActions()  # noqa: E501
        pass


if __name__ == "__main__":
    unittest.main()
