project:
  type: website
  output-dir: _build

website:
  # title: "Cloud-Py"
  description: "TileDB's Cloud Client for Python"
  repo-url: https://github.com/TileDB-Inc/TileDB-Cloud-Py/
  favicon: "t_favicon.png"
  page-navigation: true
  navbar:
    background: light
    logo: "TileDB_logo_primary.png"
    pinned: true
    left:
      - text: Get Started
        file: get_started.qmd
      - text: API
        file: reference/index.qmd

  sidebar:
    style: "floating"
    collapse-level: 1
    contents:
      - section: Catalog
        contents:
          - text: groups
            href: reference/groups.qmd
          - text: array
            href: reference/array.qmd
          - text: asset
            href: reference/asset.qmd
          - text: files
            href: reference/files.qmd
          - text: notebook
            href: reference/notebook.qmd
          - text: udf
            href: reference/udf.qmd

      - section: Collaborate
        contents:
          - text: groups
            href: reference/groups.qmd
          - text: array
            href: reference/array.qmd
          - text: asset
            href: reference/asset.qmd
          - text: invites
            href: reference/invites.qmd

      - section: Analyze
        contents:
          - text: bioimg.exportation
            href: reference/bioimg.exportation.qmd
          - text: bioimg.helpers
            href: reference/bioimg.helpers.qmd
          - text: bioimg.ingestion
            href: reference/bioimg.ingestion.qmd
          - text: files.indexing
            href: reference/files.indexing.qmd
          - text: files.ingestion
            href: reference/files.ingestion.qmd
          - text: files.udfs
            href: reference/files.udfs.qmd
          - text: files.utils
            href: reference/files.utils.qmd
          - text: geospatial.ingestion
            href: reference/geospatial.ingestion.qmd
          - text: soma.ingest
            href: reference/soma.ingest.qmd
          - text: soma.mapper
            href: reference/soma.mapper.qmd
          - text: vcf.allele_frequency
            href: reference/vcf.allele_frequency.qmd
          - text: vcf.ingestionq
            href: reference/vcf.ingestion.qmd
          - text: vcf.query
            href: reference/vcf.query.qmd
          - text: vcf.utils
            href: reference/vcf.utils.qmd
          - text: vcf.split
            href: reference/vcf.split.qmd

      - section: Scale
        contents:
          - text: cloudarray
            href: reference/cloudarray.qmd
          - text: compute.delayed
            href: reference/compute.delayed.qmd
          - text: dag.dag
            href: reference/dag.dag.qmd
          - text: dag.mode
            href: reference/dag.mode.qmd
          - text: dag.status
            href: reference/dag.status.qmd
          - text: dag.visualization
            href: reference/dag.visualization.qmd
          - text: tasks
            href: reference/tasks.qmd
          - text: udf
            href: reference/udf.qmd
          - text: utilities.consolidate
            href: reference/utilities.consolidate.qmd
          - text: utilities.profiler
            href: reference/utilities.profiler.qmd

      - section: Account
        contents:
          - text: client
            href: reference/client.qmd
          - text: config
            href: reference/config.qmd

quartodoc:
  style: pkgdown
  parser: sphinx
  package: tiledb.cloud
  title: API Reference

  options:
    include_classes: true
    include_functions: true
    include_attributes: true

  sections:
    - title: Catalog
      desc: PLACEHOLDER CATEGORY DESCRIPTION
      contents:
        - groups
        - array
        - asset
        - files
        - notebook
        - udf

    - title: Collaborate
      desc: PLACEHOLDER CATEGORY DESCRIPTION
      contents:
        - groups
        - array
        - asset
        - invites

    - title: Analyze
      desc: PLACEHOLDER CATEGORY DESCRIPTION

    - subtitle: Bio Imaging
      contents:
        - bioimg.exportation
        - bioimg.helpers
        - bioimg.ingestion

    - subtitle: Files
      contents:
        - files.indexing
        - files.ingestion
        - files.udfs
        - files.utils

    - subtitle: Geospatial
      contents:
        - geospatial.ingestion

    - subtitle: SOMA
      contents:
        - soma.ingest
        - soma.mapper

    - subtitle: VCF
      contents:
        - vcf.allele_frequency
        - vcf.ingestion
        - vcf.query
        - vcf.utils
        - vcf.split

    - title: Scale
      desc: PLACEHOLDER CATEGORY DESCRIPTION
      contents:
        - cloudarray
        - compute.delayed
        - dag.dag
        - dag.mode
        - dag.status
        - dag.visualization
        - tasks
        - udf
        - utilities.consolidate
        - utilities.profiler

    - title: Account
      desc: PLACEHOLDER CATEGORY DESCRIPTION
      contents:
        - client
        - config
