# asset { #tiledb.cloud.asset }

`cloud.asset`

An asset may be an array or a group.

## Functions

| Name | Description |
| --- | --- |
| [delete](#tiledb.cloud.asset.delete) | Deregister the asset and remove its physical groups and arrays from storage. |
| [info](#tiledb.cloud.asset.info) | Retrieve information about an asset. |

### delete { #tiledb.cloud.asset.delete }

`cloud.asset.delete(uri, recursive=False)`

Deregister the asset and remove its physical groups and arrays from storage.

#### Parameters

| Name   | Type   | Description              | Default    |
|--------|--------|--------------------------|------------|
| `uri`  | str    | tiledb URI of the asset. | _required_ |

#### Returns

| Type   | Description   |
|--------|---------------|
| None   | None.         |

### info { #tiledb.cloud.asset.info }

`cloud.asset.info(uri)`

Retrieve information about an asset.

#### Parameters

| Name   | Type   | Description              | Default    |
|--------|--------|--------------------------|------------|
| `uri`  | str    | tiledb URI of the asset. | _required_ |

#### Returns

| Type                          | Description             |
|-------------------------------|-------------------------|
| Union\[ArrayInfo, GroupInfo\] | ArrayInfo or GroupInfo. |
