# exportation { #tiledb.cloud.bioimg.exportation }

`cloud.bioimg.exportation`



## Functions

| Name | Description |
| --- | --- |
| [export](#tiledb.cloud.bioimg.exportation.export) | The function exports microscopy images from TileDB arrays |

### export { #tiledb.cloud.bioimg.exportation.export }

`cloud.bioimg.exportation.export(source, output, *args, access_credentials_name, config=None, taskgraph_name=None, num_batches=None, resources=None, compute=True, mode=Mode.BATCH, namespace=None, verbose=False, output_ext='tiff', **kwargs)`

The function exports microscopy images from TileDB arrays

#### Parameters

| Name                      | Type                            | Description                                                                                                            | Default      |
|---------------------------|---------------------------------|------------------------------------------------------------------------------------------------------------------------|--------------|
| `source`                  | Union\[Sequence\[str\], str\]   | uri / iterable of uris of input files If the uri points to a directory of files make sure it ends with a trailing '/'  | _required_   |
| `output`                  | Union\[Sequence\[str\], str\]   | uri / iterable of uris of input files. If the uri points to a directory of files make sure it ends with a trailing '/' | _required_   |
| `config`                  | Optional\[Mapping\[str, Any\]\] | dict configuration to pass credentials of the destination                                                              | `None`       |
| `taskgraph_name`          | Optional\[str\]                 | Optional name for taskgraph, defaults to None                                                                          | `None`       |
| `num_batches`             | Optional\[int\]                 | Number of graph nodes to spawn. Performs it sequentially if default, defaults to 1                                     | `None`       |
| `threads`                 |                                 | Number of threads for node side multiprocessing, defaults to 8                                                         | _required_   |
| `resources`               | Optional\[Mapping\[str, Any\]\] | configuration for node specs e.g. {"cpu": "8", "memory": "4Gi"}, defaults to None                                      | `None`       |
| `compute`                 | bool                            | When True the DAG returned will be computed inside the function otherwise DAG will only be returned.                   | `True`       |
| `mode`                    | Optional\[Mode\]                | By default runs Mode.Batch                                                                                             | `Mode.BATCH` |
| `run_on`                  |                                 | By default runs on server if value is "client" runs client side.                                                       | _required_   |
| `namespace`               | Optional\[str\]                 | The namespace where the DAG will run                                                                                   | `None`       |
| `verbose`                 | bool                            | verbose logging, defaults to False                                                                                     | `False`      |
| `access_credentials_name` | str                             | Access Credentials Name (ACN) registered in TileDB Cloud (ARN type)                                                    | _required_   |
| `output_ext`              | str                             | extension for the output images in tiledb                                                                              | `'tiff'`     |
