# file { #tiledb.cloud.file }

`cloud.file`



## Functions

| Name | Description |
| --- | --- |
| [create_file](#tiledb.cloud.file.create_file) | Creates a TileDB file at the specified location |
| [export_file](#tiledb.cloud.file.export_file) | Exports a TileDB File back to its original file format |
| [export_file_local](#tiledb.cloud.file.export_file_local) | Exports a TileDB File back to its original file format |

### create_file { #tiledb.cloud.file.create_file }

`cloud.file.create_file(namespace, input_uri, output_uri, name=None, access_credentials_name=None, access_credential_name=None, async_req=False)`

Creates a TileDB file at the specified location

#### Parameters

| Name                      | Type            | Description                                         | Default    |
|---------------------------|-----------------|-----------------------------------------------------|------------|
| `namespace`               | str             | namespace the create file operation belongs to      | _required_ |
| `name`                    | Optional\[str\] | name to use for registration in TileDB Cloud        | `None`     |
| `input_uri`               | str             | input file uri                                      | _required_ |
| `output_uri`              | str             | output array uri                                    | _required_ |
| `access_credential_name`  | Optional\[str\] | DEPRECATED. Use ``access_credential_name`` instead. | `None`     |
| `access_credentials_name` | Optional\[str\] | optional access credentials to use                  | `None`     |
| `async_req`               | bool            | return future instead of results for async support  | `False`    |

#### Returns

| Type               | Description                                             |
|--------------------|---------------------------------------------------------|
| models.FileCreated | FileCreated details, including file_uuid and output_uri |

### export_file { #tiledb.cloud.file.export_file }

`cloud.file.export_file(uri, output_uri, async_req=False)`

Exports a TileDB File back to its original file format

#### Parameters

| Name         | Type   | Description                                        | Default    |
|--------------|--------|----------------------------------------------------|------------|
| `uri`        | str    | The ``tiledb://...`` URI of the file to export     | _required_ |
| `output_uri` | str    | output file uri                                    | _required_ |
| `async_req`  | bool   | return future instead of results for async support | `False`    |

#### Returns

| Type                | Description                                |
|---------------------|--------------------------------------------|
| models.FileExported | FileExported details, including output_uri |

### export_file_local { #tiledb.cloud.file.export_file_local }

`cloud.file.export_file_local(uri, output_uri, timestamp=None, async_req=False)`

Exports a TileDB File back to its original file format

#### Parameters

| Name         | Type   | Description                                                                                                                     | Default    |
|--------------|--------|---------------------------------------------------------------------------------------------------------------------------------|------------|
| `uri`        | str    | The ``tiledb://...`` URI of the file to export                                                                                  | _required_ |
| `output_uri` | str    | output file uri                                                                                                                 | _required_ |
| `timestamp`  | tuple  | (default None) If int, open the array at a given TileDB timestamp. If tuple, open at the given start and end TileDB timestamps. | `None`     |
| `async_req`  | bool   | return future instead of results for async support                                                                              | `False`    |

#### Returns

| Type                | Description                                |
|---------------------|--------------------------------------------|
| models.FileExported | FileExported details, including output_uri |
