# ingest { #tiledb.cloud.soma.ingest }

`cloud.soma.ingest`



## Functions

| Name | Description |
| --- | --- |
| [build_ingest_workflow_graph](#tiledb.cloud.soma.ingest.build_ingest_workflow_graph) | Same signature as ``run_ingest_workflow``, but returns the graph object |
| [ingest_h5ad](#tiledb.cloud.soma.ingest.ingest_h5ad) | Performs the actual work of ingesting H5AD data into TileDB. |
| [run_ingest_workflow](#tiledb.cloud.soma.ingest.run_ingest_workflow) | Starts a workflow to ingest H5AD data into SOMA. |
| [run_ingest_workflow_udf](#tiledb.cloud.soma.ingest.run_ingest_workflow_udf) | This is the highest-level ingestor component that runs on-node. Only here |

### build_ingest_workflow_graph { #tiledb.cloud.soma.ingest.build_ingest_workflow_graph }

`cloud.soma.ingest.build_ingest_workflow_graph(output_uri, input_uri, measurement_name, pattern=None, extra_tiledb_config=None, platform_config=None, ingest_mode='write', resources=None, namespace=None, access_credentials_name=None, logging_level=logging.INFO, dry_run=False)`

Same signature as ``run_ingest_workflow``, but returns the graph object
directly.

### ingest_h5ad { #tiledb.cloud.soma.ingest.ingest_h5ad }

`cloud.soma.ingest.ingest_h5ad(output_uri, input_uri, measurement_name, extra_tiledb_config, platform_config, ingest_mode, logging_level=logging.INFO, dry_run=False)`

Performs the actual work of ingesting H5AD data into TileDB.

#### Parameters

| Name                  | Type                            | Description                                                                                                                  | Default    |
|-----------------------|---------------------------------|------------------------------------------------------------------------------------------------------------------------------|------------|
| `output_uri`          | str                             | The output URI to write to. This will probably look like ``tiledb://namespace/some://storage/uri``.                          | _required_ |
| `input_uri`           | str                             | The URI of the H5AD file to read from. This file is read using TileDB VFS, so any path supported (and accessible) will work. | _required_ |
| `measurement_name`    | str                             | The name of the Measurement within the Experiment to store the data.                                                         | _required_ |
| `extra_tiledb_config` | Optional\[Dict\[str, object\]\] | Extra configuration for TileDB.                                                                                              | _required_ |
| `platform_config`     | Optional\[Dict\[str, object\]\] | The SOMA ``platform_config`` value to pass in, if any.                                                                       | _required_ |
| `ingest_mode`         | str                             | One of the ingest modes supported by ``tiledbsoma.io.read_h5ad``.                                                            | _required_ |
| `dry_run`             | bool                            | If provided and set to ``True``, does the input-path traversals without ingesting data.                                      | `False`    |

### run_ingest_workflow { #tiledb.cloud.soma.ingest.run_ingest_workflow }

`cloud.soma.ingest.run_ingest_workflow(output_uri, input_uri, measurement_name, pattern=None, extra_tiledb_config=None, platform_config=None, ingest_mode='write', resources=None, namespace=None, access_credentials_name=None, logging_level=logging.INFO, dry_run=False)`

Starts a workflow to ingest H5AD data into SOMA.

#### Parameters

| Name                      | Type                            | Description                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      | Default    |
|---------------------------|---------------------------------|------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|------------|
| `output_uri`              | str                             | The output URI to write to. This will probably look like ``tiledb://namespace/some://storage/uri``.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              | _required_ |
| `input_uri`               | str                             | The URI of the H5AD file(s) to read from. These are read using TileDB VFS, so any path supported (and accessible) will work.  If the ``input_uri`` passes ``vfs.is_file``, it's ingested.  If the ``input_uri`` passes ``vfs.is_dir``, then all first-level entries are ingested .  In the latter, directory case, an input file is skipped if ``pattern`` is provided and doesn't match the input file. As well, in the directory case, each entry's basename is appended to the ``output_uri`` to form the entry's output URI. For example, if ``a.h5ad` and ``b.h5ad`` are present within ``input_uri`` of ``s3://bucket/h5ads/`` and ``output_uri`` is ``tiledb://namespace/s3://bucket/somas``, then ``tiledb://namespace/s3://bucket/somas/a`` and ``tiledb://namespace/s3://bucket/somas/b`` are written. | _required_ |
| `measurement_name`        | str                             | The name of the Measurement within the Experiment to store the data.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             | _required_ |
| `pattern`                 | Optional\[str\]                 | As described for ``input_uri``.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  | `None`     |
| `extra_tiledb_config`     | Optional\[Dict\[str, object\]\] | Extra configuration for TileDB.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  | `None`     |
| `platform_config`         | Optional\[Dict\[str, object\]\] | The SOMA ``platform_config`` value to pass in, if any.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           | `None`     |
| `ingest_mode`             | str                             | One of the ingest modes supported by ``tiledbsoma.io.read_h5ad``.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                | `'write'`  |
| `resources`               | Optional\[Dict\[str, object\]\] | A specification for the amount of resources to provide to the UDF executing the ingestion process, to override the default.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      | `None`     |
| `namespace`               | Optional\[str\]                 | An alternate namespace to run the ingestion process under.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       | `None`     |
| `access_credentials_name` | Optional\[str\]                 | If provided, the name of the credentials to pass to the executing UDF.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           | `None`     |
| `dry_run`                 | bool                            | If provided and set to ``True``, does the input-path traversals without ingesting data.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          | `False`    |

#### Returns

| Type             | Description                                                                                                                                                            |
|------------------|------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
| Dict\[str, str\] | A dictionary of ``{"status": "started", "graph_id": ...}``, with the UUID of the graph on the server side, which can be used to manage execution and monitor progress. |

### run_ingest_workflow_udf { #tiledb.cloud.soma.ingest.run_ingest_workflow_udf }

`cloud.soma.ingest.run_ingest_workflow_udf(output_uri, input_uri, measurement_name, carry_along, pattern=None, extra_tiledb_config=None, platform_config=None, ingest_mode='write', resources=None, namespace=None, access_credentials_name=None, logging_level=logging.INFO, dry_run=False)`

This is the highest-level ingestor component that runs on-node. Only here
can we do VFS with access_credentials_name -- that does not work correctly
on the client.
