# invites { #tiledb.cloud.invites }

`cloud.invites`



## Functions

| Name | Description |
| --- | --- |
| [accept_invitation](#tiledb.cloud.invites.accept_invitation) | Accept an invitation. |
| [cancel_invite_to_array](#tiledb.cloud.invites.cancel_invite_to_array) | Cancels array sharing invitation. |
| [cancel_invite_to_group](#tiledb.cloud.invites.cancel_invite_to_group) | Cancels group sharing invitation. |
| [cancel_invite_to_organization](#tiledb.cloud.invites.cancel_invite_to_organization) | Cancels join organization invitation. |
| [fetch_invitations](#tiledb.cloud.invites.fetch_invitations) | Fetches a paginated list of invitations. |
| [invite_to_array](#tiledb.cloud.invites.invite_to_array) | Share array by email invite. |
| [invite_to_group](#tiledb.cloud.invites.invite_to_group) | Sends email to multiple recipients with sharing information regarding a group. |
| [invite_to_organization](#tiledb.cloud.invites.invite_to_organization) | Sends email to multiple recipients with joining information |

### accept_invitation { #tiledb.cloud.invites.accept_invitation }

`cloud.invites.accept_invitation(invitation_id)`

Accept an invitation.

#### Parameters

| Name            | Type   | Description                                | Default    |
|-----------------|--------|--------------------------------------------|------------|
| `invitation_id` | str    | the ID of invitation about to be accepted. | _required_ |

#### Returns

| Type   | Description   |
|--------|---------------|
| None   | None          |

### cancel_invite_to_array { #tiledb.cloud.invites.cancel_invite_to_array }

`cloud.invites.cancel_invite_to_array(uri, *, invitation_id)`

Cancels array sharing invitation.

#### Parameters

| Name            | Type   | Description                                             | Default    |
|-----------------|--------|---------------------------------------------------------|------------|
| `uri`           | str    | URI of array in the form 'tiledb://<namespace>/<array>' | _required_ |
| `invitation_id` | str    | the ID of invitation about to be canceled.              | _required_ |

#### Returns

| Type   | Description   |
|--------|---------------|
| None   | None          |

### cancel_invite_to_group { #tiledb.cloud.invites.cancel_invite_to_group }

`cloud.invites.cancel_invite_to_group(uri, *, invitation_id)`

Cancels group sharing invitation.

#### Parameters

| Name            | Type   | Description                                             | Default    |
|-----------------|--------|---------------------------------------------------------|------------|
| `uri`           | str    | URI of group in the form 'tiledb://<namespace>/<group>' | _required_ |
| `invitation_id` | str    | the ID of invitation about to be canceled.              | _required_ |

#### Returns

| Type   | Description   |
|--------|---------------|
| None   | None          |

### cancel_invite_to_organization { #tiledb.cloud.invites.cancel_invite_to_organization }

`cloud.invites.cancel_invite_to_organization(organization, *, invitation_id)`

Cancels join organization invitation.

#### Parameters

| Name            | Type   | Description                                | Default    |
|-----------------|--------|--------------------------------------------|------------|
| `organization`  | str    | name or UUID of organization.              | _required_ |
| `invitation_id` | str    | the ID of invitation about to be canceled. | _required_ |

#### Returns

| Type   | Description   |
|--------|---------------|
| None   | None          |

### fetch_invitations { #tiledb.cloud.invites.fetch_invitations }

`cloud.invites.fetch_invitations(**filters)`

Fetches a paginated list of invitations.

#### Parameters

| Name           | Type   | Description                                                                       | Default    |
|----------------|--------|-----------------------------------------------------------------------------------|------------|
| `organization` | str    | name or ID of organization to filter                                              | _required_ |
| `array`        | str    | name/uri of array that is url-encoded to filter                                   | _required_ |
| `group`        | str    | name or ID of group to filter                                                     | _required_ |
| `start`        | int    | start time for tasks to filter by                                                 | _required_ |
| `end`          | int    | end time for tasks to filter by                                                   | _required_ |
| `page`         | int    | pagination offset                                                                 | _required_ |
| `per_page`     | int    | pagination limit                                                                  | _required_ |
| `type`         | str    | invitation type, "ARRAY_SHARE", "JOIN_ORGANIZATION"                               | _required_ |
| `status`       | str    | Filter to only return "PENDING", "ACCEPTED"                                       | _required_ |
| `orderby`      | str    | sort by which field valid values include timestamp, array_name, organization_name | _required_ |

#### Returns

| Type   | Description                          |
|--------|--------------------------------------|
|        | Invitations and pagination metadata. |

### invite_to_array { #tiledb.cloud.invites.invite_to_array }

`cloud.invites.invite_to_array(uri, *, recipients, actions)`

Share array by email invite.

#### Parameters

| Name         | Type            | Description                                             | Default    |
|--------------|-----------------|---------------------------------------------------------|------------|
| `uri`        | str             | URI of array in the form 'tiledb://<namespace>/<array>' | _required_ |
| `recipients` | Sequence\[str\] | list of recipient emails/usernames.                     | _required_ |
| `actions`    | Sequence\[str\] | list of ArrayActions allowed to the recipient.          | _required_ |

#### Returns

| Type   | Description   |
|--------|---------------|
| None   | None          |

### invite_to_group { #tiledb.cloud.invites.invite_to_group }

`cloud.invites.invite_to_group(uri, *, recipients, array_actions, group_actions)`

Sends email to multiple recipients with sharing information regarding a group.

#### Parameters

| Name            | Type            | Description                                             | Default    |
|-----------------|-----------------|---------------------------------------------------------|------------|
| `uri`           | str             | URI of group in the form 'tiledb://<namespace>/<group>' | _required_ |
| `recipients`    | Sequence\[str\] | list of recipient emails/usernames.                     | _required_ |
| `array_actions` | Sequence\[str\] | list of ArrayActions allowed to the recipient.          | _required_ |
| `group_actions` | Sequence\[str\] | list of GroupActions allowed to the recipient.          | _required_ |

#### Returns

| Type   | Description   |
|--------|---------------|
| None   | None          |

### invite_to_organization { #tiledb.cloud.invites.invite_to_organization }

`cloud.invites.invite_to_organization(organization, *, recipients, role)`

Sends email to multiple recipients with joining information
regarding an organization.

#### Parameters

| Name           | Type            | Description                         | Default    |
|----------------|-----------------|-------------------------------------|------------|
| `organization` | str             | name or UUID of organization.       | _required_ |
| `recipients`   | Sequence\[str\] | list of recipient emails/usernames. | _required_ |
| `role`         | str             | role assigned to the recipient.     | _required_ |

#### Returns

| Type   | Description   |
|--------|---------------|
| None   | None          |
