# tasks { #tiledb.cloud.tasks }

`cloud.tasks`



## Functions

| Name | Description |
| --- | --- |
| [fetch_results](#tiledb.cloud.tasks.fetch_results) | Fetches the results of a previously-executed UDF or SQL query. |
| [fetch_results_pandas](#tiledb.cloud.tasks.fetch_results_pandas) | Fetches the results of a previously-executed UDF or SQL query. |
| [last_sql_task](#tiledb.cloud.tasks.last_sql_task) | Fetch the last run sql array task |
| [last_udf_task](#tiledb.cloud.tasks.last_udf_task) | Fetch the last run udf task |
| [task](#tiledb.cloud.tasks.task) | Fetch a single array task |
| [tasks](#tiledb.cloud.tasks.tasks) | Fetch all tasks a user has access too |

### fetch_results { #tiledb.cloud.tasks.fetch_results }

`cloud.tasks.fetch_results(task_id, *, result_format=None)`

Fetches the results of a previously-executed UDF or SQL query.

### fetch_results_pandas { #tiledb.cloud.tasks.fetch_results_pandas }

`cloud.tasks.fetch_results_pandas(task_id, *, result_format=models.ResultFormat.NATIVE)`

Fetches the results of a previously-executed UDF or SQL query.

### last_sql_task { #tiledb.cloud.tasks.last_sql_task }

`cloud.tasks.last_sql_task()`

Fetch the last run sql array task

#### Returns

| Type   | Description              |
|--------|--------------------------|
|        | object with task details |

### last_udf_task { #tiledb.cloud.tasks.last_udf_task }

`cloud.tasks.last_udf_task()`

Fetch the last run udf task

#### Returns

| Type   | Description              |
|--------|--------------------------|
|        | object with task details |

### task { #tiledb.cloud.tasks.task }

`cloud.tasks.task(id, async_req=False)`

Fetch a single array task

#### Parameters

| Name        | Type   | Description                                        | Default    |
|-------------|--------|----------------------------------------------------|------------|
| `id`        | str    | id to lookup                                       | _required_ |
| `async_req` |        | return future instead of results for async support | `False`    |

#### Returns

| Type   | Description              |
|--------|--------------------------|
|        | object with task details |

### tasks { #tiledb.cloud.tasks.tasks }

`cloud.tasks.tasks(namespace=None, array=None, start=None, end=datetime.datetime.utcnow(), status=None, page=None, per_page=None, async_req=False)`

Fetch all tasks a user has access too

#### Parameters

| Name        | Type     | Description                                                                | Default                      |
|-------------|----------|----------------------------------------------------------------------------|------------------------------|
| `namespace` | str      | optional filter by namespace                                               | `None`                       |
| `array`     | str      | optional limit tasks to specific array                                     | `None`                       |
| `start`     | datetime | optional start time for listing of tasks, defaults to 7 days ago           | `None`                       |
| `end`       | datetime | optional end time for listing of tasks defaults to now                     | `datetime.datetime.utcnow()` |
| `status`    | str      | optional filter on status can be one of ['FAILED', 'RUNNING', 'COMPLETED'] | `None`                       |
| `page`      | int      | optional page for pagenating results                                       | `None`                       |
| `per_page`  | int      | optional records to return per page                                        | `None`                       |
| `async_req` |          | return future instead of results for async support                         | `False`                      |

#### Returns

| Type   | Description   |
|--------|---------------|
|        |               |
